name: 00 - Sanity
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ Actions ok para ${{ github.repository }} @ ${{ github.ref }}"