name: CI - Build (no push)
on:
  push:
    branches: [ main, "feat/**", "fix/**", "hotfix/**", "release/**" ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: ./app-exemplo
          push: false
          tags: temp/test:latest
