name: CI - Build & Push (GHCR)

on:
  push:
    branches: [ main, "feat/**", "fix/**", "hotfix/**", "release/**" ]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # necessário para publicar no GHCR
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set vars (repo lowercase e tag)
        id: vars
        shell: bash
        run: |
          echo "IMAGE_REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=${GITHUB_REF_NAME}-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "IMAGE_URL=ghcr.io/${GITHUB_REPOSITORY,,}/app-exemplo" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./app-exemplo
          push: true
          tags: |
            ${{ steps.vars.outputs.IMAGE_URL }}:${{ steps.vars.outputs.IMAGE_TAG }}
            ${{ steps.vars.outputs.IMAGE_URL }}:latest
